name: Deploy to GitHub Pages
on:
  push:
    branches:
    - master
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0'

    - name: Publish .NET
      run: dotnet publish szalapski.github.io.csproj -c Release -o release --nologo

    # add .nojekyll file to tell GitHub pages to allow files and folders starting with an underscore)
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll

    # add .gitattributes file to tell GitHub pages to allow JS pages not as text
    - name: Add .gitattributes file
      run: echo "*.js binary" >> .gitattributes

    # copy index.html to 404.html to overcome lack of server-side routing on Github Pages. TODO:
    #   alternative 1: https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-6.0#github-pages
    #   alternative 2: https://swimburger.net/blog/dotnet/pre-render-blazor-webassembly-at-build-time-to-optimize-for-search-engines
    - name: copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html

    - name: Deploy to Github Pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: $
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: release/wwwroot # The folder the action should deploy.
        SINGLE_COMMIT: true